export const productTypes = {

    GETALL_REQUEST: 'PRODUCTS_GETALL_REQUEST',
    GETALL_SUCCESS: 'PRODUCTS_GETALL_SUCCESS',
    GETALL_FAILURE: 'PRODUCTS_GETALL_FAILURE',

    DELETE_REQUEST: 'PRODUCT_DELETE_REQUEST',
    DELETE_SUCCESS: 'PRODUCT_DELETE_SUCCESS',
    DELETE_FAILURE: 'PRODUCT_DELETE_FAILURE',

};
